CREATE OR REPLACE PROCEDURE PRC_INSERIR_ALUNO(P_MAT ALUNOS.MATRICULA%TYPE,
											 P_N ALUNOS.NOME%TYPE,
											 P_IDADE ALUNOS.IDADE%TYPE,
											 P_TP_SEXO ALUNOS.SEXO%TYPE ,
											 P_TURMA ALUNOS.TURMA%TYPE,
											 P_UF ALUNOS.UF%TYPE ,
											 P_CIDADE ALUNOS.CIDADE%TYPE ,
											 P_PERIODO ALUNOS.PERIODO%TYPE,
 			   								 P_FK_CURSO ALUNOS.FK_CURSO%TYPE)
 LANGUAGE 'plpgsql'	
AS $$

BEGIN

IF (P_MAT IS NOT NULL) THEN
INSERT INTO ALUNOS VALUES (P_MAT,P_N, P_IDADE, P_TP_SEXO,P_TURMA,P_UF , P_CIDADE , P_PERIODO ,P_FK_CURSO);
END IF;

IF (P_TP_SEXO IS NULL OR P_UF IS NULL OR P_CIDADE IS NULL) THEN
INSERT INTO ALUNOS VALUES (P_MAT,P_N, P_IDADE, P_TURMA,P_PERIODO ,P_FK_CURSO);
END IF;


END;
$$
